package com.jacstuff.sketchy.brushes;

public enum BrushShape {
    CIRCLE, SQUARE, LINE, STRAIGHT_LINE, ROUNDED_RECTANGLE,
    TRIANGLE, PENTAGON, HEXAGON, STAR, ARC, TEXT, TEXT_ON_CIRCLE,
    WAVY_LINE, PATH, OVAL, CRESCENT, ASTROID, DRAG_RECTANGLE, X, DIAMOND,
    POINTED_OVAL, BANANA, TRAPEZOID, CURVE, PARALLELOGRAM, TRIANGLE_ARBITRARY, RANDOM, SPIRAL, CRAZY_SPIRAL, VARIABLE_CIRCLE
}
