package com.jacstuff.sketchy.brushes;

public enum BrushShape {
    CIRCLE, SQUARE, LINE, STRAIGHT_LINE, ROUNDED_RECTANGLE,
    TRIANGLE, PENTAGON, HEXAGON, STAR, ARC, TEXT, TEXT_ON_CIRCLE,
    WAVY_LINE, PATH, OVAL, CRESCENT, BANANA, DRAG_RECTANGLE, X, DIAMOND,
    LENS, CONVEX_SQUARE
}
